! Fix Type Conditions
integer, public :: BC_FIX_DENSITY
integer, public :: BC_FIX_X_SPEED
integer, public :: BC_FIX_Y_SPEED
integer, public :: BC_FIX_Z_SPEED
integer, public :: BC_FIX_PRESSURE

! Copy Type Conditions
integer, public :: BC_COPY_DENSITY
integer, public :: BC_COPY_X_SPEED
integer, public :: BC_COPY_Y_SPEED
integer, public :: BC_COPY_Z_SPEED
integer, public :: BC_COPY_PRESSURE

! Misc Conditions
integer, public :: BC_FLOW_TANGENCY
integer, public :: BC_NO_SLIP
integer, public :: BC_PERIODIC
integer, public :: BC_INTERFACE
