#compiler options
program := FEST3D
FC 			 = $(GFC)
FFLAGS	 = $(GFFLAGS)
MODOPT   = $(GMODOPT) 
VPATH 	:= src
BINDIR	:= bin
OBJDIR	:= obj
MODDIR	:= mod
GFC 		:= mpif90
#IFC 		:= scorep mpif90 -f90=ifort
IFC 		:= mpifort -fc=ifort
#IFC 		:= /usr/local/mpich/bin/mpifort
GMODOPT := J
IMODOPT := module


MAKEFLAGS += --silent
GFFLAGS	:= -Og -Wall -Wextra -Wconversion \
	        -ffree-line-length-256 \
					-Wno-compare-reals \
					-fdefault-real-8 \
					-Waliasing \
					-Wsurprising \
					-Wintrinsic-shadow \
					-pedantic-errors \
					-fbounds-check \
					-cpp
					#-Werror \

IFFLAGS := -O3 -g -free -r8 -traceback \
					 -L/sware/intel/mkl/lib/intel64 \
           -cpp \
					 -zero \
					 -u \
					 -W1 \
					 -warn \
					 -warn error \
					 -warn declaration \
					 -warn uncalled \
					 -warn unused
           
include files

objects = $(addprefix $(OBJDIR)/, $(files:.f90=.o))
modules = $(addprefix $(MODDIR)/, $(files:.f90=.mod))
src     = $(addprefix $(VPATH)/, $(files))
exe     = $(BINDIR)/$(program)


#path to python program that make dependency
# $(DEP_FILE) is a .dep file generated by fort_depend.py
MAKEDEPEND = python fort_depend.py
DEP_FILE = makefile.dep

all: $(exe) $(DEP_FILE)  PREMAKE

# PREMAKE to list all fortran files in src/
# make sub-directories in obj/
.PHONY: PREMAKE
PREMAKE : files

files : premake.py
	python premake.py


# Make dependencies
.PHONY: depend 
depend: $(DEP_FILE)

# The .dep file depends on the source files, so it automatically gets updated
# when you change your source
$(DEP_FILE): $(OBJECTS) files
	@echo "Making dependencies!"
#	$(MAKEDEPEND) -w -v -b $(OBJDIR) -o $(DEP_FILE)
	$(MAKEDEPEND) -w -b $(OBJDIR) -o $(DEP_FILE) -f $(src)

include $(DEP_FILE)
         
$(exe) : $(objects)
	@echo "  Making executable "
	$(FC)  $(objects) -o $(exe) -$(MODOPT)$(MODDIR)/
	echo Compilation Successful

$(OBJDIR)/%.o : %.f90
	@echo "  Compiling:     $(basename $(notdir $<))"
	$(FC) $(FFLAGS) -c $< -o $@  -$(MODOPT)$(MODDIR)


.PHONY: clean
clean:
	rm -f $(objects) $(modules) $(exe) makefile.dep


tar:
	tar -zcvf fest3d.tar.gz $(OBJDIR)/ $(MODDIR)/ $(BINDIR)/ $(VPATH)/ setup.sh makefile \
		makefile.dep fort_depend.py archive/ 

