#compiler options
program := FEST3D
subprog := wall
FC 			 = $(GFC)
FFLAGS	 = $(GFFLAGS)
VPATH 	:= src
BINDIR	:= bin
OBJDIR	:= obj
MODDIR	:= mod
GFC 		:= mpif90
IFC 		:= mpif90 -f90=ifort
#IFC 		:= mpiifort
GFFLAGS	:= -O3 -Wall -Wextra -Wconversion \
					-Wno-compare-reals \
					-fdefault-real-8 \
					-Waliasing \
					-Wsurprising \
					-Wintrinsic-shadow \
					-pedantic-errors \
					-fbounds-check \
					-Werror \
					-cpp

IFFLAGS := -O3 -free -r8 -traceback \
           -cpp \
					 -zero \
					 -u \
					 -W1 \
					 -warn \
					 -warn error \
					 -warn declaration \
					 -warn uncalled \
					 -warn unused
subpath:= resnorm \
				 resnorm/viscous \
				 resnorm/turbulent

include files


subfiles = global.f90 \
					 global_vars.f90 \
					 utils.f90 \
					 grid.f90 \
					 wall_find.f90 \
					 surfnode.f90 \
					 wall_main.f90 


objects = $(addprefix $(OBJDIR)/, $(files:.f90=.o))
objects = $(addprefix $(OBJDIR)/, $(files:.f90=.o))
modules = $(addprefix $(MODDIR)/, $(files:.f90=.mod))
src     = $(addprefix $(VPATH)/, $(files))
subobjects = $(addprefix $(OBJDIR)/, $(notdir $(subfiles:.f90=.o)))
submodules = $(addprefix $(MODDIR)/, $(notdir $(subfiles:.f90=.mod)))
exe = $(BINDIR)/$(program)
pre = $(BINDIR)/$(subprog)

#path to python program that make dependency
MAKEDEPEND = python fort_depend.py
# $(DEP_FILE) is a .dep file generated by fort_depend.py
DEP_FILE = makefile.dep

all: $(exe) $(DEP_FILE)  PREMAKE

# PREMAKE to list all fortran files in src/
# make sub-directories in obj/
.PHONY: PREMAKE
PREMAKE : files

files : premake.py
	python premake.py


# Make dependencies
.PHONY: depend 
depend: $(DEP_FILE)

# The .dep file depends on the source files, so it automatically gets updated
# when you change your source
$(DEP_FILE): $(OBJECTS) files
	@echo "Making dependencies!"
#	$(MAKEDEPEND) -w -v -b $(OBJDIR) -o $(DEP_FILE)
	$(MAKEDEPEND) -w -b $(OBJDIR) -o $(DEP_FILE) -f $(src)

include $(DEP_FILE)
         
$(exe) : $(objects)
ifeq ($(FC), mpif90)
	$(FC)  $(objects) -o $(exe) -J$(MODDIR)/
else
	$(FC)  $(objects) -o $(exe) -module $(MODDIR)
endif

$(OBJDIR)/%.o : %.f90 | setup 
ifeq ($(FC), mpif90)
	$(FC) $(FFLAGS) -c  $< -o $@ -J$(MODDIR)/
else
	$(FC) $(FFLAGS) -c  $< -o $@ -module $(MODDIR)/ 
endif

#$(pre) : $(subobjects)
#ifeq ($(FC), mpif90)
#	$(FC)  $(subobjects) -o $(pre) -J$(MODDIR)/
#else
#	$(FC)   $(FFLAGS) -c src/wall_main.f90  -module $(MODDIR)
#	$(FC)  $(subobjects) -o $(pre) -module $(MODDIR)
#endif


.PHONY: setup
setup:
#	@if test ! -d $(OBJDIR); then mkdir $(OBJDIR); else : ; fi
#	@if test ! -d $(MODDIR); then mkdir $(MODDIR); else : ; fi
#	@if test ! -d $(BINDIR); then mkdir $(BINDIR); else : ; fi
#	@if test ! -d $(OBJDIR)/resnorm; then mkdir $(OBJDIR)/resnorm; else : ; fi
#	@if test ! -d $(OBJDIR)/resnorm/viscous; then mkdir $(OBJDIR)/resnorm/viscous; else : ; fi
#	@if test ! -d $(OBJDIR)/resnorm/turbulent; then mkdir $(OBJDIR)/resnorm/turbulent; else : ; fi
#	@if test ! -d $(OBJDIR)/read_write; then mkdir $(OBJDIR)/read_write; else : ; fi
#	@if test ! -d $(OBJDIR)/read_write/read; then mkdir $(OBJDIR)/read_write/read; else : ; fi
#	@if test ! -d $(OBJDIR)/read_write/write; then mkdir $(OBJDIR)/read_write/write; else : ; fi
#	@if test ! -d $(OBJDIR)/transport; then mkdir $(OBJDIR)/transport; else : ; fi
#	@if test ! -d $(OBJDIR)/transport/viscosity; then mkdir $(OBJDIR)/transport/viscosity; else : ; fi
#	@if test ! -d $(OBJDIR)/transport/viscosity/molecular; then mkdir $(OBJDIR)/transport/viscosity/molecular; else : ; fi
#	@if test ! -d $(OBJDIR)/transport/viscosity/turbulent; then mkdir $(OBJDIR)/transport/viscosity/turbulent; else : ; fi
#	@if test ! -d $(OBJDIR)/source; then mkdir $(OBJDIR)/source; else : ; fi

.PHONY: clean
clean:
	rm -f $(objects) $(modules) $(exe) makefile.dep files

tar:
	tar -zcvf fest3d.tar.gz $(OBJDIR)/ $(MODDIR)/ $(BINDIR)/ $(VPATH)/ setup.sh makefile \
		makefile.dep fort_depend.py archive/ 

