! should be included in face_interpoant.f90 file 

    real, dimension(:, :, :), pointer :: x_tk_left, x_tk_right
    real, dimension(:, :, :), pointer :: y_tk_left, y_tk_right
    real, dimension(:, :, :), pointer :: z_tk_left, z_tk_right
    real, dimension(:, :, :), pointer :: x_te_left, x_te_right
    real, dimension(:, :, :), pointer :: y_te_left, y_te_right
    real, dimension(:, :, :), pointer :: z_te_left, z_te_right

    !public member
!    public :: x_tk_left, x_tk_right
!    public :: y_tk_left, y_tk_right
!    public :: z_tk_left, z_tk_right
!    public :: x_te_left, x_te_right
!    public :: y_te_left, y_te_right
!    public :: z_te_left, z_te_right
