!should be included in ausm before variable deceleration
! import module face_interploant 
!  do not use select case

    include "turbulence_models/sst/ausm/import_module.inc"
    include "turbulence_models/kkl/ausm/import_module.inc"
    include "turbulence_models/sa/ausm/import_module.inc"
    include "turbulence_models/kw/ausm/import_module.inc"
    include "turbulence_models/ke/ausm/import_module.inc"
    include "turbulence_models/des-sst/ausm/import_module.inc"

