! should be included in face_interpoant.f90 file 

    real, dimension(:, :, :), pointer :: x_tk_left, x_tk_right
    real, dimension(:, :, :), pointer :: y_tk_left, y_tk_right
    real, dimension(:, :, :), pointer :: z_tk_left, z_tk_right
    real, dimension(:, :, :), pointer :: x_tkl_left, x_tkl_right
    real, dimension(:, :, :), pointer :: y_tkl_left, y_tkl_right
    real, dimension(:, :, :), pointer :: z_tkl_left, z_tkl_right

    !public member
!    public :: x_tk_left, x_tk_right
!    public :: y_tk_left, y_tk_right
!    public :: z_tk_left, z_tk_right
!    public :: x_tkl_left, x_tkl_right
!    public :: y_tkl_left, y_tkl_right
!    public :: z_tkl_left, z_tkl_right
