!should be included in face_nterpolant.f90 file
            
            ! Unlink xi faces left pointers
            nullify(x_tv_left)

            ! Unlink xi faces right pointers
            nullify(x_tv_right)

            ! Unlink eta faces left pointers
            nullify(y_tv_left)

            ! Unlink eta faces right pointers
            nullify(y_tv_right)
            
            ! Unlink tau faces left pointers
            nullify(z_tv_left)

            ! Unlink tau faces right pointers
            nullify(z_tv_right)


