!should be included in ausmUP before variable deceleration
! import module face_interploant 
!  do not use select case

    include "turbulence_models/sst/ausmUP/import_module.inc"
    include "turbulence_models/kkl/ausmUP/import_module.inc"
    include "turbulence_models/sa/ausmUP/import_module.inc"
    include "turbulence_models/kw/ausmUP/import_module.inc"
    include "turbulence_models/ke/ausmUP/import_module.inc"
    include "turbulence_models/des-sst/ausmUP/import_module.inc"

