!should be included in ausmP before variable deceleration
! import module face_interploant 
!  do not use select case

    include "turbulence_models/sst/ausmP/import_module.inc"
    include "turbulence_models/kkl/ausmP/import_module.inc"
    include "turbulence_models/sa/ausmP/import_module.inc"
    include "turbulence_models/kw/ausmP/import_module.inc"
    include "turbulence_models/ke/ausmP/import_module.inc"
    include "turbulence_models/des-sst/ausmP/import_module.inc"

